### ISSUE TITLE
"Error": "open index.html: no such file or directory"

### ISSUE THREAD

**Issue by davisford** [tmc/ssaview#4]
``` sh
$go get github.com/tmc/ssaview
$ssaview &
[1] 41036
$open http://localhost:8080
```

![screen shot 2016-04-12 at 5 28 15 am](https://cloud.githubusercontent.com/assets/186677/14455791/6634401e-006f-11e6-9198-43ceaaefe91a.png)

**Comment by tmc** [comment]
the binary expects the index.html file to be in the working directory. Using something like https://github.com/rakyll/statik could remove this dependency.
